services:
  mysql:
    image: mysql:9.2.0
    restart: always
    container_name: mysql
    volumes:
      - ./config/init/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      #  数据库还原目录 可将需要还原的sql文件放在这里
      - ./.cache/mysql/data:/docker-entrypoint-initdb.d
      - ./config/init/mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.cache/mysql/log:/var/log/mysql
      - ./.cache/mysql/lib:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=blog"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin -u root -proot ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      blog_network:
        ipv4_address: 172.28.0.2

  redis:
    image: redis:7.0.4
    restart: always
    container_name: "redis"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - ./config/init/redis/redis.conf:/etc/redis/redis.conf
      - ./.cache/redis/data:/data
    networks:
      blog_network:
        ipv4_address: 172.28.0.3
    
  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch
    hostname: opensearch
    restart: always
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - ./.cache/opensearch/data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin" # modify password
    networks:
      blog_network:
        ipv4_address: 172.28.0.4

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch_dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://localhost:9200","http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    restart: always
    networks:
      blog_network:
        ipv4_address: 172.28.0.5

  maxwell:
    image: zendesk/maxwell:v1.43.2
    container_name: maxwell
    depends_on:
      - redis
      - mysql
      - opensearch
      - rabbitmq
    restart: always
    command: "bin/maxwell --config /app/config.properties"
    # 172.18.0.X neets to set host.
    # command: "bin/maxwell --user='root' --password='root'  --host='172.18.0.4'  --producer=rabbitmq --rabbitmq_user='guest' --rabbitmq_pass='guest' --rabbitmq_host='172.18.0.5' --rabbitmq_port='5672' --rabbitmq_exchange='maxwell_exchange'  --rabbitmq_exchange_type='fanout' --rabbitmq_exchange_durable='true'" # --filter='exclude: *.*, include: blog.t_article.article_title = *, include: blog.t_article.article_content = *, include: blog.t_article.is_delete = *, include: blog.t_article.status = *'
    volumes:
      - "./config/init/maxwell/config.properties:/app/config.properties"
    networks:
      blog_network:
        ipv4_address: 172.28.0.6

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    # hostname: rabbitmq
    environment:
      # - "RABBITMQ_DEFAULT_VHOST=/"
      - "RABBITMQ_DEFAULT_USER=guest"
      - "RABBITMQ_DEFAULT_PASS=guest"
    volumes:
      - ./.cache/rabbitmq/lib:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      blog_network:
        ipv4_address: 172.28.0.7


# docker network create --driver bridge blog_network
networks:
  blog_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
