spring:
  application:
    name: Blog
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Shanghai
    #  返回时间戳
    serialization:
      write-dates-as-timestamps: true

  mail:
    host: smtp.126.com
    username: rx_ted@126.com
    password: WFbSTRf8QfcVQmYt
    port: 25
    protocol: smtp
    test-connection: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: root # Redis 服务器密码。
      database: 0 # Redis 数据库号，默认为 0。
      timeout: 1000 # Redis 连接超时时间，单位：毫秒。
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数，默认为 8 。使用负数表示没有限制。
          max-idle: 8 # 默认连接数最小空闲的连接数，默认为 8 。使用负数表示没有限制。
          min-idle: 0 # 默认连接池最小空闲的连接数，默认为 0 。允许设置 0 和 正数。
          max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1 ，表示不限制。

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3000

  elasticsearch:
    username: guest
    password: guest
    uris:
      - localhost:9200
    rest:
      uris: localhost:9200

  cache:
    type: redis
    redis:
      time-to-live: 6000

knife4j:
  enable: true

openapi:
  title: blog API接口文档
  description: Blog Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://rx-ted.asia
  contact:
    name: rx-ted
    url: https://rx-ted.asia
    email: gjy.18sui@gmail.com

# logging:
#   file:
#     name: "logging.log"

search:
  # only select one
  # mode: mysql
  mode: opensearch

jwt:
  secret: ThisIsASecretThisIsASecretThisIsASecretThisIsASecret #rx-ted
  expiration: 3600
  refresh-token:
    expiration: 604800000 # 7 天
  header: "Authorization"
  prefix: "Bearer "

opensearch:
  uris: http://localhost:9200
  username: admin
  password: admin
  host: localhost
  port: 9200
  protocol: http
  keyStorePath: # cert path
  keyStorePassword: # cert password
  index_name: article

upload:
  mode: oss
  oss:
    url: http://Bucket域名/
    endpoint: OSS配置endpoint
    accessKeyId: OSS配置accessKeyId
    accessKeySecret: OSS配置accessKeySecret
    bucketName: OSS配置bucketName
  minio:
    url: http://minio的ip:9000/
    endpoint: http://minio的ip:9000
    accesskey: 用户名
    secretKey: 密码
    bucketName: 桶的名称

qq:
  app-id: QQ APPID
  check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
  user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # debug log
    map-underscore-to-camel-case: true

ip:
  ip2region: "/ip/ip2region.db"

website:
  url: https://rx-ted.asia

# logging:
#   level:
#     org:
#       springframework: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev

# 应用服务 WEB 访问端口
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
# 应用服务 WEB 访问端口
server:
  port: 80
